# 1. Write a Python Program to Add Two Matrices?

In [8]:
import numpy as np
M1=np.array([[12,120,19],[94,12,3]])
print(f"matrix 1: \n{M1}")
M2=np.array([[34,89,90],[90,76,56]])
print(f"matrix 2: \n{M2}")
print(f"The addition of the 2 matrices: \n{M1+M2}")

matrix 1: 
[[ 12 120  19]
 [ 94  12   3]]
matrix 2: 
[[34 89 90]
 [90 76 56]]
The addition of the 2 matrices: 
[[ 46 209 109]
 [184  88  59]]


# 2. Write a Python Program to Multiply Two Matrices?

In [16]:
import numpy as np
M1=np.array([[1,2,6],[2,3,4],[5,7,9]])
print(M1)
M2=np.array([[1,2],[3,4],[5,6]])
print(M2)
print(f"The mulplication of the matrices is: \n{M1.dot(M2)}")

[[1 2 6]
 [2 3 4]
 [5 7 9]]
[[1 2]
 [3 4]
 [5 6]]
The mulplication of the matrices is: 
[[37 46]
 [31 40]
 [71 92]]


# 3. Write a Python Program to Transpose a Matrix?

In [31]:
import numpy as np
M=np.array([[1,2,4],[12,23,12],[12,278,90]])
print(M)
print(f"The transpose of the matrix is: \n{M.transpose()}")

[[  1   2   4]
 [ 12  23  12]
 [ 12 278  90]]
The transpose of the matrix is: 
[[  1  12  12]
 [  2  23 278]
 [  4  12  90]]


# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [43]:
string="An apple a day keeps the doctor away"
words=string.split()
words_lower=[i.lower() for i in words]
print("The sorted words are:")
print(sorted(words_lower))

The sorted words are:
['a', 'an', 'apple', 'away', 'day', 'doctor', 'keeps', 'the']


# 5. Write a Python Program to Remove Punctuation From a String?

In [56]:
import string
newstr="Ineuron, is the best org. in the _ world????!!@@@"
for a in string.punctuation:
    newstr=newstr.replace(a,"")
print(f"Removed punctuation: \n{newstr}")

Removed punctuation: 
Ineuron is the best org in the  world
